### ISSUE TITLE
is Debian 8 (Jessie) no logner supported?

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#4574]
Commit https://github.com/qTox/qTox/commit/90910cbfe14f78fd3f03ce6318953967c05ec1c0 upped Qt version to 5.5.

Debian 8 does not have 5.5, only 5.3.

Meanwhile, [INSTALL.md](https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/INSTALL.md#debian-1) states that Debian 8 is supported.

So how it is in the end?

**Comment by Talkless** [comment]
Yep, it does not build on Debian 8 due to Qt 5.4 new enum value:
```
error: ‘AppDataLocation’ is not a member of ‘QStandardPaths’
location = QStandardPaths::AppDataLocation;
```

**Comment by Diadlo** [comment]
@Talkless Yes, we support only current stable Debian. I.e. Debian 9

**Comment by Talkless** [comment]
Well, it could be supported until it hits LTS-mode... 

So INSTALL.md needs updating I guess.

**Comment by Diadlo** [comment]
Unfortunately, Debian move forward too slow. It's hard to maintain so old version of Qt packages
