### PR TITLE
fix(build): do not build unix-specific test on Windows

### LINKED ISSUE #4735: Windows build fails due to the use of Posix identifiers
Broken by #4701

Errors:

```
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp: In member function ‘void TestPosixSignalNotifier::checkUsrSignalHandling()’:
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:42:21: error: ‘SIGUSR1’ was not declared in this scope
     psn.watchSignal(SIGUSR1);
                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:44:27: error: ‘kill’ was not declared in this scope
     kill(getpid(), SIGUSR1);
                           ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp: In member function ‘void TestPosixSignalNotifier::checkIgnoreExtraSignals()’:
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:62:21: error: ‘SIGUSR1’ was not declared in this scope
     psn.watchSignal(SIGUSR1);
                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:66:12: error: ‘SIGUSR2’ was not declared in this scope
     signal(SIGUSR2, sighandler);
            ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:67:27: error: ‘kill’ was not declared in this scope
     kill(getpid(), SIGUSR2);
                           ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp: In member function ‘void TestPosixSignalNotifier::checkTermSignalsHandling()’:
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:83:53: error: ‘SIGHUP’ was not declared in this scope
     const std::initializer_list<int> termSignals = {SIGHUP, SIGINT, SIGQUIT, SIGTERM};
                                                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:83:69: error: ‘SIGQUIT’ was not declared in this scope
     const std::initializer_list<int> termSignals = {SIGHUP, SIGINT, SIGQUIT, SIGTERM};
                                                                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:83:85: error: could not convert ‘{<expression error>, 2, <expression error>, 15}’ from ‘<brace-enclosed initializer list>’ to ‘const std::initializer_list<int>’
     const std::initializer_list<int> termSignals = {SIGHUP, SIGINT, SIGQUIT, SIGTERM};
                                                                                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:86:30: error: ‘kill’ was not declared in this scope
         kill(getpid(), signal);
                              ^
CMakeFiles/test_posixsignalnotifier.dir/build.make:63: recipe for target 'CMakeFiles/test_posixsignalnotifier.dir/test/platform/posixsignalnotifier_test.cpp.obj' failed
```

[Build log](https://build.tox.chat/job/qTox-cmake-nightly_build_windows_x86_release/19/console) (will disappear after some time).

### PR DESCRIPTION
**Pull request by Talkless**
Modify CMake file to build posixsignalnotifier test only on UNIX-like systems.

Tested by cross-building for Windows within Ubuntu 16.04 container, and building natively on Debian 9 (stretch).

Closes #4735

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4737)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4737#-:-KwRi_6oo20VKEgapMAb:b-jbsf8z)*
