### ISSUE TITLE
[Regression] Atomic build error

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#3899]
##### Brief Description

OS: Slackware Linux 32bit
qTox version: v1.6.0
Commit hash:  af91885
GCC: 5.4.0

Reproducible: Always 

##### Steps to reproduce

1. Clone qtox repo
2. Try to build

##### Observed Behavior
```
compiling moc_profileimporter.cpp
moc src/widget/form/settings/userinterfaceform.h compiling moc_userinterfaceform.cpp
linking qtox
/usr/lib/gcc/i586-slackware-linux/5.4.0/../../../../i586-slackware-linux/bin/ld: videoframe.o: undefined reference to symbol В«__atomic_fetch_add_8@@LIBATOMIC_1.0В»
/usr/lib/libatomic.so.1: error adding symbols: DSO missing from command line 
```

##### Expected Behavior
Normal build

##### Additional Info
Build was successful about May

**Comment by Diadlo** [comment]
~~@initramfs~~

```
4ac20c7b460b5207237bcfe0becd10b8b3be0f60 is the first bad commit
commit 4ac20c7b460b5207237bcfe0becd10b8b3be0f60
Author: initramfs <cputerminator@hotmail.com>
Date:   Sun May 1 12:36:32 2016 +0800

    feat(video): adds an ID parameter to the VideoSource class

:100644 100644 1327fd25a526914711c4c53b97ff9878426e9ff1 ef53ee79b7f8e2333c0ca2789538fa953dca4689 M      qtox.pro
:040000 040000 4a5aee17a6943be44ce871697a74c92afdec77a3 039e8c43616a23a4500f38d57c9e3683a5617296 M      src
```

**Added:** Seems, it's qmake problem. It add `i486` as arch on `i686` and ignore manual added `march` CXX parameter

**Comment by Diadlo** [comment]
The workaround: after qmake, execute next command:

```
sed -i -e "s/march=[a-z0-9\-]* /march=native /" Makefile
```

**Comment by zetok** [comment]
Migrating to CMake will fix it, right?

**Comment by Diadlo** [comment]
@zetok Yes, I think so

**Comment by Diadlo** [comment]
Should be fixed now. IDK, why I reopen it :)
