### ISSUE TITLE
Does not compile on Qt 5.2.1

### ISSUE THREAD

**Issue by Talkless** [qTox/qTox#2812]
On Kubuntu 14.04 I got:

```
in file included from src/widget/about/aboutuser.cpp:2:0:
./ui_aboutuser.h: In member function ‘void Ui_AboutUser::retranslateUi(QDialog*)’:
./ui_aboutuser.h:210:15: error: ‘class QPlainTextEdit’ has no member named ‘setPlaceholderText’
         note->setPlaceholderText(QApplication::translate("AboutUser", "You can save comment about this contact here.", 0));
```

While:

```
$ qmake --version
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
```

[Qt documentation](http://doc.qt.io/qt-5/qplaintextedit.html#placeholderText-prop) states that QPlainTextEdit::setPlaceholderText() introduced in Qt 5.3.

**Comment by tux3** [comment]
Making this compatible with Qt 5.2 is probably going to be nontrivial.
Since even Debian stable is already at Qt 5.3.2, I think it should be reasonable to up the requirement to Qt 5.3 minimum now.

@Talkless As a Kubuntu 14.04 user, is it reasonably possible for you to update Qt to 5.3?

**Comment by agilob** [comment]
Disabling only screenshoting would work.

**Comment by Talkless** [comment]
I guess I could, I just tried to compile it with "stock" 14.04, and now I see that PPA provides statically linked qTox... I shouldn't had to report this bug at all...

**Comment by agilob** [comment]
It was reported before, we had to increase Qt version to implement screenshoting properly.

Ok, this one is not about screenshoting ;) I think you still need qt5.4  to compile qtox, another dependency that is used for SS requires it.

**Comment by tux3** [comment]
Okay, from our side it's probably better to up the requirement to Qt 5.3. Thanks for reporting the breakage though, I'll update the documentation.

**Comment by tux3** [comment]
@agilob Our Debian stable machine on the Tox Jenkins builds packages with Qt 5.3.2, so if it ever breaks we'll know easily :)

**Comment by roranicus** [comment]
I dunno if it's okay for me to comment on a closed issue, but anyone knows how I'd go around updating Qt on Linux Mint? I installed it, but qmake --version still returns the older version.

**Comment by agilob** [comment]
One way, you can apt-get remove your qt packages and compile from sources, install newer version from alien-packages. We don't recommend any of those versions, better just wait for your distro to update qt packages.

**Comment by roranicus** [comment]
yeah, I'd be worried it would affect other software that depends on it. I guess the next best thing would be to compile from debian in a virtual box or something. Thanks.

**Comment by Talkless** [comment]
@roranicus you installed it form online installer (https://www.qt.io/download-open-source/) ?

You either have to update PATH variable so it contains path something like `/opt/Qt/5.3/gcc_64/bin' (wherever it is actually installed):

```
export PATH="/opt/Qt/5.3/gcc_64/bin:${PATH}"
qmake --version
```

Or you could add that export line into `/etc/profile.d/qt.sh` file for example.

Or simply call `/opt/Qt/5.3/gcc_64/bin/qmake` directly when needed to use that specific version of Qt.

**Comment by roranicus** [comment]
@Talkless That's exactly what I needed, and it worked. I called the specific version with qmake, as you suggested. Thanks!

**Comment by Talkless** [comment]
@roranicus glad it helped. Have fun.
