### ISSUE TITLE
Windows build fails due to the use of Posix identifiers

### ISSUE THREAD

**Issue by nurupo** [qTox/qTox#4735]
Broken by #4701

Errors:

```
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp: In member function ‘void TestPosixSignalNotifier::checkUsrSignalHandling()’:
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:42:21: error: ‘SIGUSR1’ was not declared in this scope
     psn.watchSignal(SIGUSR1);
                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:44:27: error: ‘kill’ was not declared in this scope
     kill(getpid(), SIGUSR1);
                           ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp: In member function ‘void TestPosixSignalNotifier::checkIgnoreExtraSignals()’:
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:62:21: error: ‘SIGUSR1’ was not declared in this scope
     psn.watchSignal(SIGUSR1);
                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:66:12: error: ‘SIGUSR2’ was not declared in this scope
     signal(SIGUSR2, sighandler);
            ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:67:27: error: ‘kill’ was not declared in this scope
     kill(getpid(), SIGUSR2);
                           ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp: In member function ‘void TestPosixSignalNotifier::checkTermSignalsHandling()’:
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:83:53: error: ‘SIGHUP’ was not declared in this scope
     const std::initializer_list<int> termSignals = {SIGHUP, SIGINT, SIGQUIT, SIGTERM};
                                                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:83:69: error: ‘SIGQUIT’ was not declared in this scope
     const std::initializer_list<int> termSignals = {SIGHUP, SIGINT, SIGQUIT, SIGTERM};
                                                                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:83:85: error: could not convert ‘{<expression error>, 2, <expression error>, 15}’ from ‘<brace-enclosed initializer list>’ to ‘const std::initializer_list<int>’
     const std::initializer_list<int> termSignals = {SIGHUP, SIGINT, SIGQUIT, SIGTERM};
                                                                                     ^
/home/jenkins/workspace/qTox-cmake-nightly_build_windows_x86_release/test/platform/posixsignalnotifier_test.cpp:86:30: error: ‘kill’ was not declared in this scope
         kill(getpid(), signal);
                              ^
CMakeFiles/test_posixsignalnotifier.dir/build.make:63: recipe for target 'CMakeFiles/test_posixsignalnotifier.dir/test/platform/posixsignalnotifier_test.cpp.obj' failed
```

[Build log](https://build.tox.chat/job/qTox-cmake-nightly_build_windows_x86_release/19/console) (will disappear after some time).
