### ISSUE TITLE
qTox is not compiling on Debian 9.4 Stretch

### ISSUE THREAD

**Issue by andriusign** [qTox/qTox#5212]
##### Brief Description

OS: Linux Debian 9.4 Stretch, kernel 4.9.0-6-amd64
qTox version: (version numbers in menu `Settings → About`)  
Reproducible: Always

##### Steps to reproduce

Compile script works in Ubuntu 18.04, but not in Debian 9.4. Also tried removing ~/qTox dirs completely and compiling fresh - still the same problem.
[build-qTox.txt](https://github.com/qTox/qTox/files/2155072/build-qTox.txt)

##### Observed Behavior
In static member function ‘static void CoreAV::groupCallCallback(void*, int, int, const int16_t*, unsigned int, uint8_t, unsigned int, void*)’:
/home/user/qTox/qTox/src/core/coreav.cpp:542:32: error: ‘class ToxGroupCall’ has no member named ‘getPeers’; did you mean ‘addPeer’?
     audio.playAudioBuffer(call.getPeers()[peer], data, samples, channels, sample_rate);
                                ^~~~~~~~
CMakeFiles/qtox_static.dir/build.make:690: recipe for target 'CMakeFiles/qtox_static.dir/src/core/coreav.cpp.o' failed
make[2]: *** [CMakeFiles/qtox_static.dir/src/core/coreav.cpp.o] Error 1
CMakeFiles/Makefile2:219: recipe for target 'CMakeFiles/qtox_static.dir/all' failed
make[1]: *** [CMakeFiles/qtox_static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

##### Expected Behavior
Compiled and working.

##### Additional Info
[compile.log](https://github.com/qTox/qTox/files/2155065/compile.log)

**Comment by sudden6** [comment]
Working on a fix, in the mean time you can upgrade you toxcore to >= 0.2.0 which works around this problem.

**Comment by sudden6** [comment]
@andriusign It should now be fixed on master, can you confirm?

EDIT: You are also using a very old version of toxcore and should probably update that.

**Comment by andriusign** [comment]
@sudden6 I can confirm that qTox is compiling now! I have also removed "git checkout v0.1.11" from my build script, because it was checking out older Toxcore version. 
Compiled things: Toxcore v0.2.3, qTox v1.15.0-88-g977b7fc9, Qt v5.7.1.
Thank you very much for the quick support. qTox is the best!

**Comment by tox-user** [comment]
You can also use our simple_make.sh build script. We update the toxcore version in it with every release.
