### ISSUE TITLE
Document minimal Qt version

### ISSUE THREAD

**Issue by xaizek** [qTox/qTox#70]
Search on GitHub or grepping sources for `Qt5`, `Qt4` or something similar gives no results.

Trying to compile with `Qt 4.8.6`.

``` bash
$ qmake
Project MESSAGE: Warning: unknown QT: multimediawidgets
```

``` bash
$ make
...
In file included from widget/form/addfriendform.cpp:1:0:
widget/form/addfriendform.h:11:22: fatal error: QDnsLookup: No such file or directory
 #include <QDnsLookup>
...
```

[Official documentation](https://qt-project.org/doc/qt-5/qdnslookup.html) says that `QDnsLookup` is available since `Qt 5.0`.

So _toxgui_ seems to require at least `Qt 5.0`, but it's not stated anywhere explicitly.

**Comment by msteinbeck** [comment]
By the way, we should also document that this project uses C++-11

**Comment by msteinbeck** [comment]
nurupo uses http://pastebin.com/gf8VAPgW to check minimal Qt version

**Comment by tux3** [comment]
The minimum required version is Qt 5.2, it might work with Qt 5.0 or 5.1 but I can't guarantee that those versions will still work in the future.

I'll update the README
