### ISSUE TITLE
Build fails: undefined reference to `OpenAL::OpenAL()'

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4380]
It was broken by 28c2298.
@sudden6 

Building using qtox.pro on FreeBSD.

```
linking qtox
audio.o: In function `Audio::getInstance()':
src/audio/audio.cpp:(.text+0x3e): undefined reference to `OpenAL::OpenAL()'
src/audio/audio.cpp:(.text+0x45): undefined reference to `OpenAL::~OpenAL()'
```

**Comment by Diadlo** [comment]
Problems with `CMakeLists.txt` still there?

**Comment by yurivict** [comment]
cmake still breaks with 1.10.0
