### ISSUE TITLE
Compiling error on ubuntu

### ISSUE THREAD

**Issue by kuradakis** [qTox/qTox#4890]
##### Brief Description

OS: Ubuntu 16.04.3
qTox: 
 root@alex-Latitude-7480:~/qTox# git log
commit a2feaf3fc6439b583b607faf955cdcb43045c793
Author: sudden6 <sudden6@gmx.at>
Date:   Thu Dec 28 11:12:46 2017 +0100

…

Reproducible: Always

##### Steps to reproduce

1. Git clone
2. Compile 
3. Error (See installation steps below)

##### Observed Behavior
Cannot compile on ubuntu 16.04.3 64bit
Error message: 
[ 31%] Building CXX object CMakeFiles/qtox_static.dir/src/core/corefile.cpp.o
[ 32%] Building CXX object CMakeFiles/qtox_static.dir/src/core/dhtserver.cpp.o
[ 32%] Building CXX object CMakeFiles/qtox_static.dir/src/core/recursivesignalblocker.cpp.o
[ 32%] Building CXX object CMakeFiles/qtox_static.dir/src/core/toxcall.cpp.o
[ 33%] Building CXX object CMakeFiles/qtox_static.dir/src/core/toxencrypt.cpp.o
[ 33%] Building CXX object CMakeFiles/qtox_static.dir/src/core/toxfile.cpp.o
/root/qTox/src/core/toxencrypt.cpp: In static member function ‘static std::unique_ptr<ToxEncrypt> ToxEncrypt::makeToxEncrypt(const QString&)’:
/root/qTox/src/core/toxencrypt.cpp:158:46: error: ‘tox_pass_key_new’ was not declared in this scope
     Tox_Pass_Key* passKey = tox_pass_key_new();
                                              ^
/root/qTox/src/core/toxencrypt.cpp:162:67: error: cannot convert ‘Tox_Pass_Key*’ to ‘const uint8_t* {aka const unsigned char*}’ for argument ‘1’ to ‘Tox_Pass_Key* tox_pass_key_derive(const uint8_t*, size_t, TOX_ERR_KEY_DERIVATION*)’
                         static_cast<size_t>(pass.length()), &error);
                                                                   ^
/root/qTox/src/core/toxencrypt.cpp: In static member function ‘static std::unique_ptr<ToxEncrypt> ToxEncrypt::makeToxEncrypt(const QString&, const QByteArray&)’:
/root/qTox/src/core/toxencrypt.cpp:198:46: error: ‘tox_pass_key_new’ was not declared in this scope
     Tox_Pass_Key* passKey = tox_pass_key_new();
                                              ^
/root/qTox/src/core/toxencrypt.cpp:202:86: error: cannot convert ‘Tox_Pass_Key*’ to ‘const uint8_t* {aka const unsigned char*}’ for argument ‘1’ to ‘Tox_Pass_Key* tox_pass_key_derive_with_salt(const uint8_t*, size_t, const uint8_t*, TOX_ERR_KEY_DERIVATION*)’
                                   static_cast<size_t>(pass.length()), salt, &keyError);
                                                                                      ^
CMakeFiles/qtox_static.dir/build.make:830: recipe for target 'CMakeFiles/qtox_static.dir/src/core/toxencrypt.cpp.o' failed
make[2]: *** [CMakeFiles/qtox_static.dir/src/core/toxencrypt.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:219: recipe for target 'CMakeFiles/qtox_static.dir/all' failed
make[1]: *** [CMakeFiles/qtox_static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
[  1%] Automatic moc for target test_toxid
[  1%] Built target test_toxid_automoc
[  1%] Automatic moc for target qtox_static
[  1%] Built target qtox_static_automoc
[  2%] Building CXX object CMakeFiles/qtox_static.dir/src/core/toxencrypt.cpp.o
/root/qTox/src/core/toxencrypt.cpp: In static member function ‘static std::unique_ptr<ToxEncrypt> ToxEncrypt::makeToxEncrypt(const QString&)’:
/root/qTox/src/core/toxencrypt.cpp:158:46: error: ‘tox_pass_key_new’ was not declared in this scope
     Tox_Pass_Key* passKey = tox_pass_key_new();
                                              ^
/root/qTox/src/core/toxencrypt.cpp:162:67: error: cannot convert ‘Tox_Pass_Key*’ to ‘const uint8_t* {aka const unsigned char*}’ for argument ‘1’ to ‘Tox_Pass_Key* tox_pass_key_derive(const uint8_t*, size_t, TOX_ERR_KEY_DERIVATION*)’
                         static_cast<size_t>(pass.length()), &error);
                                                                   ^
/root/qTox/src/core/toxencrypt.cpp: In static member function ‘static std::unique_ptr<ToxEncrypt> ToxEncrypt::makeToxEncrypt(const QString&, const QByteArray&)’:
/root/qTox/src/core/toxencrypt.cpp:198:46: error: ‘tox_pass_key_new’ was not declared in this scope
     Tox_Pass_Key* passKey = tox_pass_key_new();
                                              ^
/root/qTox/src/core/toxencrypt.cpp:202:86: error: cannot convert ‘Tox_Pass_Key*’ to ‘const uint8_t* {aka const unsigned char*}’ for argument ‘1’ to ‘Tox_Pass_Key* tox_pass_key_derive_with_salt(const uint8_t*, size_t, const uint8_t*, TOX_ERR_KEY_DERIVATION*)’
                                   static_cast<size_t>(pass.length()), salt, &keyError);
                                                                                      ^
CMakeFiles/qtox_static.dir/build.make:830: recipe for target 'CMakeFiles/qtox_static.dir/src/core/toxencrypt.cpp.o' failed
make[2]: *** [CMakeFiles/qtox_static.dir/src/core/toxencrypt.cpp.o] Error 1
CMakeFiles/Makefile2:219: recipe for target 'CMakeFiles/qtox_static.dir/all' failed
make[1]: *** [CMakeFiles/qtox_static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
root@alex-Latitude-7480:/home/alex# cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

##### Expected Behavior
To have it compiled successfully

##### Additional Info
Installation steps (in a script):

apt-get install git libexif-dev build-essential cmake libavcodec-dev libavdevice-dev libavfilter-dev libavutil-dev libgdk-pixbuf2.0-dev libglib2.0-dev libgtk2.0-dev libopenal-dev libqrencode-dev libqt5opengl5-dev libqt5svg5-dev libsqlcipher-dev libswresample-dev libswscale-dev libxss-dev qrencode qt5-default qt5-qmake qttools5-dev-tools libtool autotools-dev automake checkinstall check libopus-dev libvpx-dev libsodium-dev
apt remove utox
git clone https://github.com/toktok/c-toxcore.git /root/toxcore
cd /root/toxcore/
autoreconf -i
./configure
make -j2
make install
git clone https://github.com/qTox/qTox /root/qTox
cd /root/qTox
cmake .
make -j2
make install
ldconfig

Attached screenshot: 
![image](https://user-images.githubusercontent.com/5382056/34584674-02841564-f19d-11e7-9a17-58946daeb70b.png)

Thank you

**Comment by sudden6** [comment]
I guess this is because we have not yet updated qTox to the newest c-toxcore master. Try the c-toxcore v0.1.11 tag.

**Comment by kuradakis** [comment]
Thank you @sudden6 it fixed it.
