### PR TITLE
fix(qtox.pro): add openal.h and openal.cpp

### LINKED ISSUE #4380: Build fails: undefined reference to `OpenAL::OpenAL()'
It was broken by 28c2298.
@sudden6 

Building using qtox.pro on FreeBSD.

```
linking qtox
audio.o: In function `Audio::getInstance()':
src/audio/audio.cpp:(.text+0x3e): undefined reference to `OpenAL::OpenAL()'
src/audio/audio.cpp:(.text+0x45): undefined reference to `OpenAL::~OpenAL()'
```

### PR DESCRIPTION
**Pull request by sudden6**
fix #4380

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4383)

### CODE REVIEW

**Comment by noavarice** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4383#-:-KjhbXSqR2lxeMkRmPR8:b-jbsf8z)*

**Comment by sudden6** [comment]
Sorry wrong button

**Comment by yurivict** [comment]
+1
Please merge it.
