### ISSUE TITLE
IMPORTANT - We still can't compile on ubuntu and deb pkgs are 15 day olds...

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1885]
This is really boring, no updates for ubuntu/debian users cuz of a stupid ffmpeg library that doesn't exists...

Backtrace:

``` console
-o videoframe.o src/video/videoframe.cpp
src/video/videoframe.cpp: In member function ‘bool VideoFrame::convertToRGB24(QSize)’:
src/video/videoframe.cpp:119:35: error: ‘av_free’ was not declared in this scope
         av_free(frameRGB24->opaque);
                                   ^
src/video/videoframe.cpp:120:34: error: ‘av_frame_unref’ was not declared in this scope
         av_frame_unref(frameRGB24);
                                  ^
src/video/videoframe.cpp:121:34: error: ‘av_frame_free’ was not declared in this scope
         av_frame_free(&frameRGB24);
                                  ^
src/video/videoframe.cpp:124:31: error: ‘av_frame_alloc’ was not declared in this scope
     frameRGB24=av_frame_alloc();
                               ^
src/video/videoframe.cpp:131:105: error: ‘av_malloc’ was not declared in this scope
     uint8_t* buf = (uint8_t*)av_malloc(avpicture_get_size(AV_PIX_FMT_RGB24, size.width(), size.height()));
                                                                                                         ^
src/video/videoframe.cpp:135:34: error: ‘av_frame_free’ was not declared in this scope
         av_frame_free(&frameRGB24);
                                  ^
src/video/videoframe.cpp: In member function ‘bool VideoFrame::convertToYUV420()’:
src/video/videoframe.cpp:180:32: error: ‘av_frame_alloc’ was not declared in this scope
     frameYUV420=av_frame_alloc();
                                ^
src/video/videoframe.cpp:187:91: error: ‘av_malloc’ was not declared in this scope
     uint8_t* buf = (uint8_t*)av_malloc(avpicture_get_size(AV_PIX_FMT_RGB24, width, height));
                                                                                           ^
src/video/videoframe.cpp:191:35: error: ‘av_frame_free’ was not declared in this scope
         av_frame_free(&frameYUV420);
                                   ^
src/video/videoframe.cpp: In member function ‘void VideoFrame::releaseFrameLockless()’:
src/video/videoframe.cpp:220:35: error: ‘av_free’ was not declared in this scope
         av_free(frameOther->opaque);
                                   ^
src/video/videoframe.cpp:221:34: error: ‘av_frame_unref’ was not declared in this scope
         av_frame_unref(frameOther);
                                  ^
src/video/videoframe.cpp:222:34: error: ‘av_frame_free’ was not declared in this scope
         av_frame_free(&frameOther);
                                  ^
src/video/videoframe.cpp:226:36: error: ‘av_free’ was not declared in this scope
         av_free(frameYUV420->opaque);
                                    ^
src/video/videoframe.cpp:227:35: error: ‘av_frame_unref’ was not declared in this scope
         av_frame_unref(frameYUV420);
                                   ^
src/video/videoframe.cpp:228:35: error: ‘av_frame_free’ was not declared in this scope
         av_frame_free(&frameYUV420);
                                   ^
src/video/videoframe.cpp:232:35: error: ‘av_free’ was not declared in this scope
         av_free(frameRGB24->opaque);
                                   ^
src/video/videoframe.cpp:233:34: error: ‘av_frame_unref’ was not declared in this scope
         av_frame_unref(frameRGB24);
                                  ^
src/video/videoframe.cpp:234:34: error: ‘av_frame_free’ was not declared in this scope
         av_frame_free(&frameRGB24);
                                  ^
make: *** [videoframe.o] Error 1
```

**Comment by agilob** [comment]
Could you confirm [this solution](http://ubuntuforums.org/showthread.php?t=2219550&s=f7881b4e6db09a33b5984fae39081eea&p=13101922#post13101922):

```
sudo add-apt-repository ppa:jon-severinsson/ffmpeg
sudo apt-get update
sudo apt-get install ffmpeg
sudo apt-get install frei0r-plugins
```

**Comment by DanTheBritish** [comment]
Compiling ffmpeg from source is quite easy, I can compile fine on my Xubuntu 15.04 machine.

**Comment by linux-modder** [comment]
patch the 1881.diff in /src   same issue  exists in fedora  without that patching
the Makefile in  missing  -isystem/usr/include/ffmpeg  adn causing the failure

**Comment by linux-modder** [comment]
Or see my  PR (seeing as its  in ubuntu I'll update to reflect that )

**Comment by tux3** [comment]
FFmpeg is available in Ubuntu starting at 15.04, and there are some third party repositories if you really don't want to compile FFmpeg from source.

We're very unlikely to be dropping FFmpeg at this point, so if you want to compile qTox from source, you'll have to compile the dependencies too or update your system.
