### ISSUE TITLE
qTox fails to compile with GCC 4.8.4

### ISSUE THREAD

**Issue by Zer0-One** [qTox/qTox#1841]
I'm building from 4eab3dcbb866fac7c7dc22386e804c9187501a7f, and it fails with the following: 

```
src/widget/tool/callconfirmwidget.cpp: In constructor 'CallConfirmWidget::CallConfirmWidget(const QWidget*, const Friend&)':
src/widget/tool/callconfirmwidget.cpp:40:66: error: invalid initialization of reference of type 'const Friend&' from expression of type '<brace-enclosed initializer list>'
 rectRatio{static_cast<qreal>(rectH)/static_cast<qreal>(rectW)}
                                                              ^
Makefile:2438: recipe for target 'callconfirmwidget.o' failed
make: *** [callconfirmwidget.o] Error 1
make: *** Waiting for unfinished jobs....
 * ERROR: net-im/qtox-9999::tox-overlay failed (compile phase):
 *   emake failed
```

I'm using: `g++ (Gentoo Hardened 4.8.4 p1.4, pie-0.6.1) 4.8.4`
